In [2]:
from collections import Counter

In [3]:
def calcmedia(X):
    somatorio=0

    for x in X:
        somatorio=somatorio+x

    n=len(X)

    media = somatorio/n

    return media

In [4]:
Y=[1, 2, 3, 2, 6, 53, 5,3, 553, 43,7]
print( calcmedia(Y) )

61.63636363636363

In [5]:
import numpy as np

In [6]:
dados = np.random.normal( loc=40, scale=10, size=40000000).tolist()

In [7]:
print(calcmedia(dados))

40.00056202352832

In [8]:
import time

In [9]:
size=100000000
dados = np.random.normal( loc=40, scale=10, size=size)
start_time = time.time()
calcmedia(dados)
end_time = time.time()

print(end_time-start_time)

15.012408018112183

In [10]:
def calcmediana(X):
  X = np.sort(X)

  n= X.size

# X[0] x[1] x[2] x[3] x[4] -> n=5
# X[0] x[1] x[2] x[3]  -> n=4

  if n%2==1:
    return X[ n//2 ]

  return (X[n//2]+X[n//2 - 1])/2

  # n*n   ex bubblesort
  # n*log(n)   ex quicksort

  # 10*10 =100
  # 10*log2(10)  10*3.5 = 35

  # 10^6 * 10^6 = 10^12
  # 10^6 * log2(10^6) = 2*10^7

In [11]:
Y = [4, 5, 7,  1, 9, 10]

print(calcmediana(Y))

6.0

In [12]:
def calcmoda(X):
  contagem = Counter(X)
  return contagem.most_common(1)[0][0]

In [13]:
Y = ["4", "5", 7,  1, 3.0, int(3),int(3),int(3),int(3),int(3),int(3),int(3),int(3),int(3),int(3),int(3), 9, 10, "4", "5","4", "3", "3", "3", "3", 7, 2, 2, 5,3, 3, 3, 3, 3, 3, 3]

calcmoda(Y)

3.0

In [14]:
salario=[2000, 2000, 2400, 2500, 3000 , 5000000]

In [15]:
calcmedia(salario)

835316.6666666666

In [16]:
calcmediana(salario)

np.float64(2450.0)

In [17]:
ngols=[0,1,2,0,0,0,1,1,2]

In [18]:
calcmediana(ngols)

np.int64(1)

In [19]:
calcmoda(ngols)

0

In [20]:
calcmedia(ngols)

0.7777777777777778

In [21]:
jogo = [ 0 , 1 , 1, 2 , 20, 20, 20, 20,30, 60]

In [22]:
calcmedia(jogo)

17.4

In [23]:
import pandas as pd

In [24]:
url = "https://agdaf.com/estatistica/campeonato-brasileiro-full.csv"
df = pd.read_csv(url)

In [25]:
df.columns

Index(['ID', 'rodata', 'data', 'hora', 'mandante', 'visitante',
       'formacao_mandante', 'formacao_visitante', 'tecnico_mandante',
       'tecnico_visitante', 'vencedor', 'arena', 'mandante_Placar',
       'visitante_Placar', 'mandante_Estado', 'visitante_Estado'],
      dtype='object')

In [26]:
df.tail(20)

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
8765,8766,37,03/12/2024,20:04,Corinthians,Bahia,4-3-1-2,3-4-1-2,R. Díaz,R. Ceni,Corinthians,Neo Química Arena,3,0,SP,BA
8766,8767,37,04/12/2024,19:02,Vasco,Atletico-MG,4-1-2-1-2,3-4-3,F. Loureiro,G. Milito,Vasco,Estádio São Januário,2,0,RJ,MG
8767,8768,37,04/12/2024,20:01,Vitoria,Gremio,5-3-2,4-2-3-1,T. Carpini Barbosa,Renato Gaúcho,-,Barradão,1,1,BA,RS
8768,8769,37,04/12/2024,20:03,Criciuma,Flamengo,4-3-1-2,4-2-3-1,C. Tencati,F. Luís,Flamengo,Estádio Heriberto Hülse,0,3,SC,RJ
8769,8770,37,04/12/2024,20:04,Sao Paulo,Juventude,4-2-3-1,4-2-3-1,L. Zubeldía,F. Matias,Juventude,MorumBIS,1,2,SP,RS
8770,8771,37,04/12/2024,21:30,Atletico-GO,Fortaleza,4-2-3-1,4-2-3-1,A. Gomes,J. Vojvoda,Atletico-GO,Estádio Antônio Accioly - Atlético Goianiense,3,1,GO,CE
8771,8772,37,04/12/2024,21:30,Internacional,Botafogo-RJ,4-2-2-2,4-2-3-1,R. Machado Marques,A. Torres Gomes Araújo Amorim,Botafogo-RJ,Estádio Beira-Rio,0,1,RS,RJ
8772,8773,37,04/12/2024,21:30,Cruzeiro,Palmeiras,4-3-2-1,4-2-3-1,F. Diniz Silva,A. Moreira Ferreira,Palmeiras,Mineirão,1,2,MG,SP
8773,8775,37,05/12/2024,20:00,Athletico-PR,Bragantino,4-2-3-1,4-2-3-1,L. González,F. Seabra,Bragantino,Ligga Arena,1,2,PR,SP
8774,8774,37,05/12/2024,20:01,Fluminense,Cuiaba,4-2-3-1,4-2-3-1,L. Venker de Menezes,B. Franco,Fluminense,Maracanã,1,0,RJ,MT
8775,8777,38,08/12/2024,16:04,Juventude,Cruzeiro,4-2-3-1,4-2-3-1,F. Matias,F. Diniz Silva,Cruzeiro,Alfredo Jaconi,0,1,RS,MG
8776,8778,38,08/12/2024,16:04,Bahia,Atletico-GO,4-2-3-1,4-1-4-1,R. Ceni,A. Gomes,Bahia,Arena Fonte Nova,2,0,BA,GO
8777,8779,38,08/12/2024,16:04,Flamengo,Vitoria,4-4-2,4-3-3,F. Luís,T. Carpini Barbosa,-,Maracanã,2,2,RJ,BA
8778,8781,38,08/12/2024,16:04,Atletico-MG,Athletico-PR,4-3-3,4-3-2-1,L. Gonçalves,L. González,Atletico-MG,Arena MRV,1,0,MG,PR
8779,8782,38,08/12/2024,16:04,Botafogo-RJ,Sao Paulo,NaN,NaN,A. Torres Gomes Araújo Amorim,L. Zubeldía,Botafogo-RJ,Estádio Nilton Santos,2,1,RJ,SP
8780,8783,38,08/12/2024,16:04,Cuiaba,Vasco,4-3-3,4-3-2-1,B. Franco,F. Loureiro,Vasco,Arena Pantanal,1,2,MT,RJ
8781,8784,38,08/12/2024,16:04,Palmeiras,Fluminense,4-2-3-1,4-2-3-1,A. Moreira Ferreira,L. Venker de Menezes,Fluminense,Allianz Parque,0,1,SP,RJ
8782,8776,38,08/12/2024,16:05,Fortaleza,Internacional,4-2-3-1,4-1-2-1-2,J. Vojvoda,R. Machado Marques,Fortaleza,Arena Castelão,3,0,CE,RS
8783,8780,38,08/12/2024,16:05,Bragantino,Criciuma,4-2-3-1,4-1-2-1-2,F. Seabra,C. Tencati,Bragantino,Nabizão,5,1,SP,SC
8784,8785,38,08/12/2024,16:05,Gremio,Corinthians,4-4-2,4-3-1-2,Renato Gaúcho,R. Díaz,Corinthians,Arena do Grêmio,0,3,RS,SP

In [50]:
dft

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
1955,1956,1,13/05/2007,18:10,Sport,Santos,NaN,NaN,NaN,NaN,Sport,Ilha do Retiro,4,1,PE,SP
1965,1966,2,20/05/2007,18:10,Vasco,Sport,NaN,NaN,NaN,NaN,Vasco,São Januário,3,1,RJ,PE
1971,1972,3,27/05/2007,16:00,Gremio,Sport,NaN,NaN,NaN,NaN,Gremio,Olímpico,1,0,RS,PE
1982,1983,4,03/06/2007,16:00,Sport,Flamengo,NaN,NaN,NaN,NaN,-,Ilha do Retiro,2,2,PE,RJ
1990,1991,5,10/06/2007,16:00,Fluminense,Sport,NaN,NaN,NaN,NaN,Fluminense,Maracanã,3,0,RJ,PE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7592,7605,33,18/11/2021,20:59,Sport,Bahia,4-3-3,4-2-3-1,G. Florentín,A. Ferreira,Sport,Arena de Pernambuco,1,0,PE,BA
7610,7618,36,27/11/2021,21:30,Sao Paulo,Sport,4-4-2,4-3-3,R. Ceni,G. Florentín,Sao Paulo,Morumbi,2,0,SP,PE
7622,7615,35,03/12/2021,20:00,Sport,Flamengo,4-2-3-1,4-2-2-2,G. Florentín,M. Souza,-,Arena de Pernambuco,1,1,PE,RJ
7634,7635,37,06/12/2021,21:00,Chapecoense,Sport,4-4-2,4-2-3-1,F. Paiva Endres,G. Florentín,Sport,Arena Condá,0,1,SC,PE
7635,7642,38,09/12/2021,21:30,Sport,Athletico-PR,4-2-3-1,3-4-2-1,G. Florentín,J. Freitas,-,Arena de Pernambuco,1,1,PE,PR

In [49]:
timef = "Sport"
colcasa = "mandante"
colfora = "visitante"

gec = "mandante_Placar"
gfc = "visitante_Placar"

mask_casa = df[colcasa]==timef
mask_fora = df[colfora]==timef


dft= df[mask_casa | mask_fora]

condicoes = mask_casa[mask_casa|mask_fora]

ngols= np.where(condicoes, dft[gec], dft[gfc])
ngols

array([4, 1, 0, 2, 0, 2, 0, 4, 2, 2, 2, 1, 1, 3, 1, 2, 3, 0, 3, 0, 0, 2,
       1, 0, 1, 3, 0, 2, 4, 1, 0, 1, 1, 0, 3, 0, 1, 1, 0, 0, 2, 1, 2, 1,
       0, 1, 1, 2, 0, 2, 1, 0, 2, 3, 1, 2, 0, 0, 0, 1, 1, 3, 5, 0, 1, 0,
       2, 2, 0, 1, 0, 2, 0, 3, 2, 4, 1, 0, 2, 2, 4, 0, 1, 3, 0, 1, 3, 1,
       1, 3, 0, 0, 1, 0, 1, 1, 2, 1, 2, 0, 0, 2, 3, 0, 1, 2, 2, 1, 2, 2,
       2, 0, 1, 0, 1, 0, 2, 0, 1, 0, 3, 1, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 2, 1, 2, 1, 2, 1, 0, 1, 1, 1, 3, 1, 2, 3, 1, 2, 1, 0, 1, 2,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 2, 0, 0, 1, 2, 0, 2, 0, 3, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 2, 1, 2, 1, 2, 2, 2, 1, 4, 2, 1, 2, 1, 0, 2, 2,
       1, 3, 2, 1, 2, 2, 1, 0, 1, 3, 1, 1, 0, 0, 1, 0, 1, 1, 1, 3, 1, 3,
       4, 2, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 1, 4, 2, 0, 2, 0, 5, 2, 1, 1,
       4, 2, 2, 1, 1, 1, 0, 1, 0, 5, 0, 0, 1, 1, 1, 0, 1, 1, 1, 3, 0, 0,
       2, 2, 0, 1, 4, 0, 2, 1, 0, 1, 2, 1, 1, 3, 3, 1, 4, 0, 3, 2, 1, 0,
       0, 0, 0, 0, 1, 0, 2, 1, 1, 1, 3, 1, 1, 0, 1, 1, 2, 1, 0, 1, 2, 2,
       0, 1, 3, 3, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       2, 2, 0, 2, 4, 1, 0, 0, 0, 1, 0, 2, 3, 0, 1, 0, 0, 0, 2, 2, 0, 2,
       1, 1, 2, 0, 1, 3, 0, 0, 1, 0, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 0, 2,
       0, 1, 2, 0, 2, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 3, 1, 0, 0, 1, 0, 2, 0, 2, 1, 1, 0, 1, 1, 1])

In [60]:
rng= np.random.default_rng(seed=42)

In [73]:


idx = rng.permutation(len(ngols))

ngols = ngols[idx]
ngols
razaotrain=0.75
ngols_train = ngols[:int(len(ngols)*razaotrain)]
ngols_test = ngols[int(len(ngols)*razaotrain):]

print(len(ngols_test))
print(len(ngols_train))

modelo1 = int(np.mean(ngols_train))
print("Modelo da media: ", modelo1)

modelo2 = int(np.median(ngols_train))
print("Modelo da mediana: ", modelo2)

modelo3 = int(calcmoda(ngols_train))
print("Modelo da moda: ", modelo3)

105
313
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  0

In [89]:
np.sum(modelo1==ngols_test)

np.int64(38)

In [90]:
np.sum(modelo2==ngols_test)

np.int64(38)

In [91]:
np.sum(modelo3==ngols_test)

np.int64(36)

In [111]:
timef = "Vasco"

unicos = df["mandante"].unique()
print(unicos)

for timef in unicos:
  colcasa = "mandante"
  colfora = "visitante"
  gec = "mandante_Placar"
  gfc = "visitante_Placar"
  mask_casa = df[colcasa]==timef
  mask_fora = df[colfora]==timef

  dft= df[mask_casa | mask_fora]
  condicoes = mask_casa[mask_casa|mask_fora]
  ngols= np.where(condicoes, dft[gec], dft[gfc])
  idx = rng.permutation(len(ngols))
  ngols = ngols[idx]
  ngols
  razaotrain=0.75
  ngols_train = ngols[:int(len(ngols)*razaotrain)]
  ngols_test = ngols[int(len(ngols)*razaotrain):]
  print(len(ngols_test))
  print(len(ngols_train))
  print("Time: ",timef)
  modelo1 = int(np.mean(ngols_train))
  print("Modelo da media: ", modelo1)

  modelo2 = int(np.median(ngols_train))
  print("Modelo da mediana: ", modelo2)

  modelo3 = int(calcmoda(ngols_train))
  print("Modelo da moda: ", modelo3)
  print ("Acertos do modelo1: ", np.sum(modelo1==ngols_test)/len(ngols_test)*100)
  print ("Acertos do modelo2: ", np.sum(modelo2==ngols_test)/len(ngols_test)*100)
  print ("Acertos do modelo3: ", np.sum(modelo3==ngols_test)/len(ngols_test)*100)

['Guarani' 'Athletico-PR' 'Flamengo' 'Goias' 'Internacional' 'Criciuma'
 'Juventude' 'Fortaleza' 'Cruzeiro' 'Vitoria' 'Santos' 'Corinthians'
 'Fluminense' 'Atletico-MG' 'Coritiba' 'Gremio' 'Bahia' 'Figueirense'
 'Paysandu' 'Ponte Preta' 'Parana' 'Sao Caetano' 'Sao Paulo' 'Vasco'
 'Botafogo-RJ' 'Palmeiras' 'Brasiliense' 'Santa Cruz' 'America-RN' 'Sport'
 'Nautico' 'Ipatinga' 'Portuguesa' 'Avai' 'Santo Andre' 'Barueri'
 'Atletico-GO' 'Ceara' 'Gremio Prudente' 'America-MG' 'Chapecoense'
 'Joinville' 'CSA' 'Bragantino' 'Cuiaba']
33
97
Time:  Guarani
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  27.27272727272727
Acertos do modelo2:  27.27272727272727
Acertos do modelo3:  27.27272727272727
205
613
Time:  Athletico-PR
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  35.12195121951219
Acertos do modelo2:  35.12195121951219
Acertos do modelo3:  35.12195121951219
214
642
Time:  Flamengo
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  35.046728971962615
Acertos do modelo2:  35.046728971962615
Acertos do modelo3:  35.046728971962615
148
442
Time:  Goias
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  31.756756756756754
Acertos do modelo2:  31.756756756756754
Acertos do modelo3:  31.756756756756754
205
613
Time:  Internacional
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  39.51219512195122
Acertos do modelo2:  39.51219512195122
Acertos do modelo3:  39.51219512195122
52
154
Time:  Criciuma
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  40.38461538461539
Acertos do modelo2:  40.38461538461539
Acertos do modelo3:  40.38461538461539
81
243
Time:  Juventude
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  38.2716049382716
Acertos do modelo2:  38.2716049382716
Acertos do modelo3:  38.2716049382716
89
265
Time:  Fortaleza
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  38.20224719101123
Acertos do modelo2:  38.20224719101123
Acertos do modelo3:  38.20224719101123
186
556
Time:  Cruzeiro
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  33.33333333333333
Acertos do modelo2:  33.33333333333333
Acertos do modelo3:  33.33333333333333
109
325
Time:  Vitoria
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  31.19266055045872
Acertos do modelo2:  31.19266055045872
Acertos do modelo3:  31.19266055045872
205
613
Time:  Santos
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  34.146341463414636
Acertos do modelo2:  34.146341463414636
Acertos do modelo3:  34.146341463414636
205
613
Time:  Corinthians
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  40.97560975609756
Acertos do modelo2:  40.97560975609756
Acertos do modelo3:  40.97560975609756
214
642
Time:  Fluminense
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  38.78504672897196
Acertos do modelo2:  38.78504672897196
Acertos do modelo3:  38.78504672897196
205
612
Time:  Atletico-MG
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  30.24390243902439
Acertos do modelo2:  30.24390243902439
Acertos do modelo3:  30.24390243902439
148
442
Time:  Coritiba
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  37.16216216216216
Acertos do modelo2:  37.16216216216216
Acertos do modelo3:  37.16216216216216
194
582
Time:  Gremio
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  30.927835051546392
Acertos do modelo2:  30.927835051546392
Acertos do modelo3:  30.927835051546392
116
348
Time:  Bahia
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  34.48275862068966
Acertos do modelo2:  34.48275862068966
Acertos do modelo3:  34.48275862068966
110
328
Time:  Figueirense
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  30.909090909090907
Acertos do modelo2:  30.909090909090907
Acertos do modelo3:  30.909090909090907
34
100
Time:  Paysandu
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  20.588235294117645
Acertos do modelo2:  20.588235294117645
Acertos do modelo3:  20.588235294117645
91
271
Time:  Ponte Preta
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  31.868131868131865
Acertos do modelo2:  31.868131868131865
Acertos do modelo3:  31.868131868131865
62
186
Time:  Parana
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  32.25806451612903
Acertos do modelo2:  32.25806451612903
Acertos do modelo3:  32.25806451612903
43
129
Time:  Sao Caetano
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  25.581395348837212
Acertos do modelo2:  25.581395348837212
Acertos do modelo3:  25.581395348837212
214
642
Time:  Sao Paulo
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  32.71028037383177
Acertos do modelo2:  32.71028037383177
Acertos do modelo3:  32.71028037383177
167
499
Time:  Vasco
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  37.12574850299401
Acertos do modelo2:  37.12574850299401
Acertos do modelo3:  37.12574850299401
184
550
Time:  Botafogo-RJ
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  29.347826086956523
Acertos do modelo2:  29.347826086956523
Acertos do modelo3:  29.347826086956523
193
579
Time:  Palmeiras
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  33.67875647668394
Acertos do modelo2:  33.67875647668394
Acertos do modelo3:  33.67875647668394
11
31
Time:  Brasiliense
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  45.45454545454545
Acertos do modelo2:  45.45454545454545
Acertos do modelo3:  45.45454545454545
19
57
Time:  Santa Cruz
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  0
Acertos do modelo1:  42.10526315789473
Acertos do modelo2:  42.10526315789473
Acertos do modelo3:  31.57894736842105
10
28
Time:  America-RN
Modelo da media:  0
Modelo da mediana:  0
Modelo da moda:  0
Acertos do modelo1:  70.0
Acertos do modelo2:  70.0
Acertos do modelo3:  70.0
105
313
Time:  Sport
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  0
Acertos do modelo1:  34.285714285714285
Acertos do modelo2:  34.285714285714285
Acertos do modelo3:  37.142857142857146
48
142
Time:  Nautico
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  35.41666666666667
Acertos do modelo2:  35.41666666666667
Acertos do modelo3:  35.41666666666667
10
28
Time:  Ipatinga
Modelo da media:  0
Modelo da mediana:  0
Modelo da moda:  0
Acertos do modelo1:  10.0
Acertos do modelo2:  10.0
Acertos do modelo3:  10.0
29
85
Time:  Portuguesa
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  41.37931034482759
Acertos do modelo2:  41.37931034482759
Acertos do modelo3:  41.37931034482759
67
199
Time:  Avai
Modelo da media:  0
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  35.82089552238806
Acertos do modelo2:  29.850746268656714
Acertos do modelo3:  29.850746268656714
10
28
Time:  Santo Andre
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  60.0
Acertos do modelo2:  60.0
Acertos do modelo3:  60.0
10
28
Time:  Barueri
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  40.0
Acertos do modelo2:  40.0
Acertos do modelo3:  40.0
76
228
Time:  Atletico-GO
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  36.84210526315789
Acertos do modelo2:  36.84210526315789
Acertos do modelo3:  36.84210526315789
67
199
Time:  Ceara
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  37.3134328358209
Acertos do modelo2:  37.3134328358209
Acertos do modelo3:  37.3134328358209
10
28
Time:  Gremio Prudente
Modelo da media:  0
Modelo da mediana:  1
Modelo da moda:  0
Acertos do modelo1:  20.0
Acertos do modelo2:  50.0
Acertos do modelo3:  20.0
57
171
Time:  America-MG
Modelo da media:  0
Modelo da mediana:  1
Modelo da moda:  0
Acertos do modelo1:  28.07017543859649
Acertos do modelo2:  40.35087719298245
Acertos do modelo3:  28.07017543859649
67
198
Time:  Chapecoense
Modelo da media:  0
Modelo da mediana:  1
Modelo da moda:  0
Acertos do modelo1:  29.850746268656714
Acertos do modelo2:  35.82089552238806
Acertos do modelo3:  29.850746268656714
10
28
Time:  Joinville
Modelo da media:  0
Modelo da mediana:  0
Modelo da moda:  0
Acertos do modelo1:  60.0
Acertos do modelo2:  60.0
Acertos do modelo3:  60.0
10
28
Time:  CSA
Modelo da media:  0
Modelo da mediana:  0
Modelo da moda:  0
Acertos do modelo1:  60.0
Acertos do modelo2:  60.0
Acertos do modelo3:  60.0
48
142
Time:  Bragantino
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  50.0
Acertos do modelo2:  50.0
Acertos do modelo3:  50.0
38
114
Time:  Cuiaba
Modelo da media:  0
Modelo da mediana:  1
Modelo da moda:  0
Acertos do modelo1:  39.473684210526315
Acertos do modelo2:  42.10526315789473
Acertos do modelo3:  39.473684210526315

In [136]:
timef = "Brasiliense"
colcasa = "mandante"
colfora = "visitante"

gec = "mandante_Placar"
gfc = "visitante_Placar"

mask_casa = df[colcasa]==timef
mask_fora = df[colfora]==timef


dfc=df[mask_casa]
dff=df[mask_fora]

ngolscasa=dfc[gec]
ngolsfora=dff[gfc]
print(ngolscasa.mean())
print(ngolsfora.mean())

1.1428571428571428
1.0952380952380953

In [140]:
timef = "Ceara"
colcasa = "mandante"
colfora = "visitante"

gec = "mandante_Placar"
gfc = "visitante_Placar"

mask_casa = df[colcasa]==timef
mask_fora = df[colfora]==timef


dfc=df[mask_casa]
dff=df[mask_fora]

ngolscasa=dfc[gec]
ngolsfora=dff[gfc]

#idx = rng.permutation(len(ngolscasa))
#ngolscasa = ngolscasa[idx]

razaotrain=0.75
ngolscasa_train = ngolscasa[:int(len(ngolscasa)*razaotrain)]
ngolscasa_test = ngolscasa[int(len(ngolscasa)*razaotrain):]

print("Time: ",timef)
modelo1 = int(np.mean(ngolscasa_train))
print("Modelo da media: ", modelo1)

modelo2 = int(np.median(ngolscasa_train))
print("Modelo da mediana: ", modelo2)

modelo3 = int(calcmoda(ngolscasa_train))
print("Modelo da moda: ", modelo3)
print ("Acertos do modelo1: ", np.sum(modelo1==ngolscasa_test)/len(ngolscasa_test)*100)
print ("Acertos do modelo2: ", np.sum(modelo2==ngolscasa_test)/len(ngolscasa_test)*100)
print ("Acertos do modelo3: ", np.sum(modelo3==ngolscasa_test)/len(ngolscasa_test)*100)

Time:  Ceara
Modelo da media:  1
Modelo da mediana:  1
Modelo da moda:  2
Acertos do modelo1:  44.11764705882353
Acertos do modelo2:  44.11764705882353
Acertos do modelo3:  17.647058823529413

In [139]:
timef = "Ceara"
colcasa = "mandante"
colfora = "visitante"

gec = "mandante_Placar"
gfc = "visitante_Placar"

mask_casa = df[colcasa]==timef
mask_fora = df[colfora]==timef


dfc=df[mask_casa]
dff=df[mask_fora]

ngolscasa=dfc[gec]
ngolsfora=dff[gfc]

#idx = rng.permutation(len(ngolsfora))
#ngolsfora = ngolsfora[idx]

razaotrain=0.75
ngolsfora_train = ngolsfora[:int(len(ngolsfora)*razaotrain)]
ngolsfora_test = ngolsfora[int(len(ngolsfora)*razaotrain):]

print("Time: ",timef)
modelo1 = int(np.mean(ngolsfora_train))
print("Modelo da media: ", modelo1)

modelo2 = int(np.median(ngolsfora_train))
print("Modelo da mediana: ", modelo2)

modelo3 = int(calcmoda(ngolsfora_train))
print("Modelo da moda: ", modelo3)
print ("Acertos do modelo1: ", np.sum(modelo1==ngolsfora_test)/len(ngolsfora_test)*100)
print ("Acertos do modelo2: ", np.sum(modelo2==ngolsfora_test)/len(ngolsfora_test)*100)
print ("Acertos do modelo3: ", np.sum(modelo3==ngolsfora_test)/len(ngolsfora_test)*100)

Time:  Ceara
Modelo da media:  0
Modelo da mediana:  1
Modelo da moda:  1
Acertos do modelo1:  44.11764705882353
Acertos do modelo2:  41.17647058823529
Acertos do modelo3:  41.17647058823529

Apendice

In [32]:
data={        # [1 , 10)
    'v1': np.random.randint(1,10,8),
    'v2': np.random.randint(20,30,8)
}

dfm= pd.DataFrame(data)
dfm

   v1  v2
0   7  28
1   7  23
2   1  28
3   8  29
4   4  26
5   6  27
6   8  23
7   9  27

In [40]:
dfm['v2']<25

0    False
1     True
2    False
3    False
4    False
5    False
6     True
7    False
Name: v2, dtype: bool

In [38]:
resultados=[]

for i in range(len(dfm)):
  condicao = dfm['v2'][i]<25
  xv=dfm['v1'][i]
  xf=dfm['v2'][i]

  if condicao:
    resultados.append(xv)
  else:
    resultados.append(xf)

print(dfm)
resultados

   v1  v2
0   7  28
1   7  23
2   1  28
3   8  29
4   4  26
5   6  27
6   8  23
7   9  27

[np.int64(28),
 np.int64(7),
 np.int64(28),
 np.int64(29),
 np.int64(26),
 np.int64(27),
 np.int64(8),
 np.int64(27)]

In [39]:
[xv if condicao else xf
 for condicao, xv, xf in zip(dfm['v2']<25, dfm['v1'], dfm['v2'])]

[28, 7, 28, 29, 26, 27, 8, 27]

In [29]:
mask_casa[mask_casa|mask_fora]

1955     True
1965    False
1971    False
1982     True
1990    False
        ...
7592     True
7610    False
7622     True
7634    False
7635     True
Name: mandante, Length: 418, dtype: bool

In [30]:
dft

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
1955,1956,1,13/05/2007,18:10,Sport,Santos,NaN,NaN,NaN,NaN,Sport,Ilha do Retiro,4,1,PE,SP
1965,1966,2,20/05/2007,18:10,Vasco,Sport,NaN,NaN,NaN,NaN,Vasco,São Januário,3,1,RJ,PE
1971,1972,3,27/05/2007,16:00,Gremio,Sport,NaN,NaN,NaN,NaN,Gremio,Olímpico,1,0,RS,PE
1982,1983,4,03/06/2007,16:00,Sport,Flamengo,NaN,NaN,NaN,NaN,-,Ilha do Retiro,2,2,PE,RJ
1990,1991,5,10/06/2007,16:00,Fluminense,Sport,NaN,NaN,NaN,NaN,Fluminense,Maracanã,3,0,RJ,PE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7592,7605,33,18/11/2021,20:59,Sport,Bahia,4-3-3,4-2-3-1,G. Florentín,A. Ferreira,Sport,Arena de Pernambuco,1,0,PE,BA
7610,7618,36,27/11/2021,21:30,Sao Paulo,Sport,4-4-2,4-3-3,R. Ceni,G. Florentín,Sao Paulo,Morumbi,2,0,SP,PE
7622,7615,35,03/12/2021,20:00,Sport,Flamengo,4-2-3-1,4-2-2-2,G. Florentín,M. Souza,-,Arena de Pernambuco,1,1,PE,RJ
7634,7635,37,06/12/2021,21:00,Chapecoense,Sport,4-4-2,4-2-3-1,F. Paiva Endres,G. Florentín,Sport,Arena Condá,0,1,SC,PE
7635,7642,38,09/12/2021,21:30,Sport,Athletico-PR,4-2-3-1,3-4-2-1,G. Florentín,J. Freitas,-,Arena de Pernambuco,1,1,PE,PR

In [150]:
df['arena'].value_counts(normalize=True)*100

arena
 Maracanã                                            7.615253
 Mineirão                                            5.418327
 Morumbi                                             4.701195
 Couto Pereira                                       3.380763
 Serra Dourada                                       2.675014
                                                       ...
Castelão (CE)                                        0.011383
Estádio Paulo Constantino                            0.011383
Castelão de São Luís                                 0.011383
Estádio Joaquim Henrique Nogueira-Arena do jacaré    0.011383
Estádio Serra Dourada                                0.011383
Name: proportion, Length: 168, dtype: float64